name: sign2vec

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=21.3.1
  - tqdm=4.62.3
  - numpy=1.21.3
  - pandas=1.3.4
  - h5py=3.5.0
  - pytorch=1.8
  - torchaudio=0.8
  - torchvision=0.9
  - cudatoolkit=10.2
  - wandb=0.12.1
  - pysoundfile=0.10.2
  - pyarrow=4.0.0

  - pip:
      - sentencepiece==0.1.96
