name: SLTopicDetection

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=21.3.1
  - tqdm=4.62.3
  - numpy=1.21.3
  - pandas=1.3.4
  - h5py=3.5.0
  - pytorch=1.10
  - torchaudio
  - torchvision
  - cudatoolkit=10.2
  - wandb=0.12.1
  - pysoundfile=0.10.2
  - pyarrow=4.0.0
  - sentencepiece
  - torchvision
  - torchaudio>=0.8
