# @package _group_

common:
  fp16: false
  log_interval: 2
  wandb_project: SL_TD

task:
  _name: SL_topic_detection
  feats_type: ???
  body_parts: upperbody,lefthand,righthand
  feat_dims: "0,1,2"
  data: ???
  dict_path: ???
  normalize: true
  min_source_positions: 150
  max_source_positions: 5500
  max_target_positions: 1

dataset:
  num_workers: 0
  max_tokens: 40000  # batch_size is inferred from max_tokens, as the max num of sequences that can be fit in max_tokens
  # batch_size: 32
  skip_invalid_size_inputs_valid_test: true
  train_subset: train
  valid_subset: val
  validate_interval_updates: 500

criterion:
  _name: label_smoothed_cross_entropy

optimization:
  max_update: 6000
  lr: [1e-2]
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: [0.9, 0.998]
  weight_decay: 1e-3

lr_scheduler:
  _name: reduce_lr_on_plateau
  lr_shrink: 0.7
  lr_patience: 8
  warmup_updates: 50  # 500

checkpoint:
  keep_last_epochs: 1
  best_checkpoint_metric: acc
  maximize_best_checkpoint_metric: true
  #  restore_file: ???

model:
  _name: SL_topic_detection_LSTM

  encoder_hid_attention: true
  encoder_input_attention: false
  encoder_input_embed_size: 256
  dropout: 0.1
  encoder_cells: 1
  encoder_hidden_size: 64
  encoder_bidirectional: true
  encoder_normalize_before: true

bpe:
  _name: sentencepiece
  sentencepiece_model: ???
