# @package _group_

common:
  fp16: false
  log_interval: 2
  wandb_project: SL_TD
  reset_logging: true
  suppress_crashes: false
  profile: false
  seed: 1
  tpu: false
  cpu: true ##### check this when uploading to remote server
  log_format: null  # check hydra_train.log
  tensorboard_logdir: ./tensorboard_log

common_eval:
  model_overrides: '{}'
  ##### check this when uploading to remote server
  path: ''
  # check hydra_train.log

distributed_training:
  tpu: false
  distributed_world_size: 1
  distributed_init_method: null
  pipeline_model_parallel: false
  distributed_port: 0
  distributed_no_spawn: true
  distributed_rank: 0

is_ax: false

hooks:
  embedding: true
  out_file_embedding: ''
  attention: true
  out_file_attention: ''
  logits: true
  out_file: ''

task:
  _name: SL_topic_detection
  feats_type: ''
  body_parts: upperbody,lefthand,righthand
  feat_dims: "0,1,2"
  data: ''  # check this
  dict_path: ''
  normalize: true
  min_source_positions: 150
  max_source_positions: 5500
  max_target_positions: 1

dataset:
  num_workers: 0
  max_tokens: 20000  # check hydra_train.log
  skip_invalid_size_inputs_valid_test: true
  train_subset: train
  valid_subset: val
  dataset_split: test
  validate_interval_updates: 500
  required_batch_size_multiple: 8  # check hydra_train.log
  data_buffer_size: 10  # check hydra_train.log

criterion:
  _name: label_smoothed_cross_entropy

optimization:
  max_update: 8000
  lr: [1e-2]
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: [0.9, 0.998]
  weight_decay: 1e-3

lr_scheduler:
  _name: reduce_lr_on_plateau
  lr_shrink: 0.7
  lr_patience: 8
  warmup_updates: 5  # 500

checkpoint:
  keep_last_epochs: 1
  best_checkpoint_metric: acc
  maximize_best_checkpoint_metric: true
  checkpoint_suffix: ''
  checkpoint_shard_count: 1  # check hydra_train.log
  # restore_file: ???

model:
  _name: SL_topic_detection_LSTM

  encoder_hid_attention: true
  encoder_input_attention: false
  encoder_input_embed_size: 256  # check hydra_train.log
  dropout: 0.1  # check hydra_train.log
  encoder_cells: 1  # check hydra_train.log
  encoder_hidden_size: 64  # check hydra_train.log
  encoder_bidirectional: true  # check hydra_train.log
  encoder_normalize_before: true

bpe:
  _name: sentencepiece
  sentencepiece_model: ''
  # check this