# @package _group_
name: "Sweep SL TD LSTM spot_align"
project: SLTopicDetection
program: fairseq-hydra-train

method: grid #"grid", "random", "bayes"

metric:
  goal: maximize
  name: val/acc

parameters:
  task.feats_type:
    values: ['spot_align']
  dataset.max_tokens:
    values: [20000, 40000]
  task.normalize:
    values: [true]
  model.encoder_cells:
    values: [1, 2]
  model.encoder_bidirectional:
    values: [true]
  model.encoder_hidden_size:
    values: [64, 128, 256]
  model.dropout:
    values: [0.1]
  model.encoder_input_attention:
    values: [false]
  model.encoder_input_embed_size:
    values: [256]
  optimization.lr:
    values: [[0.1], [0.01], [0.001], [0.0001]]
  optimizer.weight_decay:
    values: [1e-3]


command:
  - ${program}
  - ${args_no_hyphens}
  - "task.data=../../../../../../data/How2Sign/spot_align"
  - "task.dict_path=../../../../../../data/How2Sign/i3d/categoryName_categoryID.csv"
  - "bpe.sentencepiece_model=/mnt/gpid08/users/alvaro.budria/pose2vec/data/How2Sign/text/spm_unigram8000_en.model"
  - "--config-dir"
  - "./config"
  - "--config-name"
  - "baseline"

